name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use your specific Node.js version (e.g., '18', '22')
          cache: 'npm' # Caches npm dependencies to speed up builds

      - name: Install dependencies
        run: npm ci # Use 'npm install' if you don't have a package-lock.json

      - name: Build Angular app for GitHub Pages
        # IMPORTANT: Replace YOUR_REPO_NAME with your actual GitHub repository name.
        # For example, if your repo is 'my-portfolio-app', use --base-href=/my-portfolio-app/
        # The output-path 'docs' is recommended for GitHub Pages, but you can use 'dist'
        # if you prefer and configure GitHub Pages to serve from 'root /' of the gh-pages branch.
        run: npm run build -- --output-path=docs --base-href=/YOUR_REPO_NAME/

      - name: Add .nojekyll file
        # This tells GitHub Pages NOT to process your site with Jekyll,
        # which is essential for Angular apps to function correctly.
        run: touch docs/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        # Uploads the 'docs' folder as the build artifact for deployment.
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs' # This must match the --output-path from the build step

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the successful completion of the 'build' job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4